routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('student', 'StudentController');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['first_name','last_name'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::all()->toArray();
        return view('student.index' , compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'first_name'  => 'required',
            'last_name'   => 'required'
        ]);

        $student = new Student([
            'first_name' => $request->get('first_name'),
            'last_name'  => $request->get('last_name')
        ]); 

        $student->save();
        return redirect()->route('student.index')->with('success', 'Data Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        return view ('student.edit',compact('student', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request ,[
            'first_name'   => 'required',
            'last_name'    => 'required'
        ]);

        $student = Student::find($id);
        $student->first_name = $request->get('first_name');
        $student->last_name = $request->get('last_name');
        $student->save();

        return redirect()->route('student.index')->with('success' , 'Data Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);

        $student->delete();
        return redirect()->route('student.index')->with('success_delete', 'Data Deleted');
    }
}

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" >
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" ></script>
    <script src="htt`ps://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>  
    <title>Laravel CRUD</title>
</head>
<body>
    <div class="container">
        @yield('content')
    </div>

</body>
</html>

resources/views/student/create.blade.php
@extends('master')

@section('content')

<div class="row">
    <div class="col-md-8 offset-2">
        <br>
        <h3 aling="center">Add Data</h3>
        <br>
        
        @if(count($errors) > 0)

        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if(\Session::has('success'))
        <div class="alert alert-success">
           <p style="margin-bottom:0">{{\Session::get('success') }}</p>
        </div>  
        @endif

        <form method="post" action="{{ route('student.store') }}">
            {{csrf_field()}}
            <div class="form-group">
                <input type="text" name="first_name" class="form-control" placeholder="Enter First Name" />
            </div>

            <div class="form-group">
                <input type="text" name="last_name" class="form-control" placeholder="Enter Last Name" />
            </div>

            <div class="form-group">
                <input type="submit"  class="btn btn-primary" placeholder="Enter Last Name" value="Submit" />
            </div>
        
        </form>

    </div>
</div>

@endsection

resources/views/student/edit.blade.php
@extends('master')

@section('content')

<div class="row">
    <div class="col-md-8 offset-2">
    <br/>
    <h3 align="center">Edit Record</h3>
    <br/>
    @if(count($errors) > 0)

    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
  
    @endif
    <form method="post" action="{{action('StudentController@update',$id) }}">
        {{csrf_field()}}

        <input type="hidden" name="_method" value="PATCH" />
        <div class="form-group">
                <input type="text" name="first_name" value="{{$student->first_name}}" class="form-control" placeholder="Enter First Name" />
            </div>

            <div class="form-group">
                <input type="text" name="last_name" value="{{$student->last_name}}"  class="form-control" placeholder="Enter Last Name" />
            </div>

            <div class="form-group">
                <input type="submit"  class="btn btn-primary" placeholder="Enter Last Name" value="Edit" />
            </div>
    </form>
    </div>
    </div>
</div>

@endsection

resources/views/student/index.blade.php
@extends('master')

@section('content')

<div class="row">
    <div class="col-md-12">
    <br/>
    <h3 align="center">Student Data </h3>
    <br/>

    @if($message = Session::get('success'))
    <div class="alert alert-success">
        <p style="margin-bottom:0" >{{$message}}</p>
    </div>
    @endif

    @if($message = Session::get('success_delete'))
    <div class="alert alert-danger">
        <p style="margin-bottom:0" >{{$message}}</p>
    </div>
    @endif

    <div align="right">
        <a href="{{route('student.create')}}" class="btn btn-primary">Add</a>
    <br/>
    <br/>
    </div>
    </div>
    <table class="table table-bordered table-striped">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        @foreach($students as $row)
            <tr>
                <td>{{$row['first_name']}}</td>
                <td>{{$row['last_name']}}</td>
                <td><a class="btn btn-warning" href="{{action('StudentController@edit', $row['id'])}}">Edit</a></td>
                <td>
                    <form method="post" class="delete_form" action="{{action('StudentController@destroy', $row['id'])}}">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="DELETE" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
 
        @endforeach
    </table>
</div>
<script>
$(document).ready(function(){
    $('.delete_form').on('submit',function(){
        if(confirm("Are you sure you want to delete it?"))
        {
            return true;
        }else
        {
            return false;
        }
    });
});
</script>

@endsection